name: K3s
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version:
          - v1.18.2-k3s1
    services:
      k3s:
        image: rancher/k3s:${{ matrix.k8s_version }}
        env:
          K3S_KUBECONFIG_OUTPUT: "/tmp/output/kubeconfig-${{ matrix.k8s_version }}"
          K3S_KUBECONFIG_MODE: "666"
        ports:
          - 6443:6443
        volumes:
          - /tmp/output:/tmp/output
        options: --privileged
    steps:
    - name: Test on k3s
      env:
        KUBECONFIG: "/tmp/output/kubeconfig-${{ matrix.k8s_version }}"
      run: |
        kubectl get nodes
        kubectl config get-contexts
        kubectl get ns
