name: K3s
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version:
          - v1.18.2-k3s1
    steps:
    - uses: debianmaster/actions-k3s@bd3f96a5e41d2fb2c64d8aa97853ce2ee4541658
      id: k3s
      with:
        version: ${{ matrix.k8s_version }}
    - name: Test on k3s
      run: |
        kubectl get nodes
        kubectl config get-contexts
